### ISSUE TITLE
Connection to KLF200 does not work

### ISSUE THREAD

**Issue by ghost** [ChrisHanuta/velux-klf200-api#6]
Hallo,
ich versuche über den HomematicIP CCU3 und dem dort installierten NodeRed (v.0.20.5) (also RedMatic v4.7.1) das KLF 200 über die API anzubinden. Leider ohne Erfolg, daher hoffe ich hier auf Unterstützung. Ich bin auf dem Gebiet des NodeRed etc. leider totaler Anfänger und komme jetzt einfach nicht mehr weiter.

In NodeRed (also RedMatic) habe ich das "node-red-contrib-velux" installiert und kann die drei Objekte (Nodes, Api, Scenes) verwenden. 
Ich ziehe die Velux Nodes rein und wähle unter DataSource die frisch eingerichtete klf200-connection aus. (Die Host-IP ist 192.168.5.1 und das Passwort ist das WLAN-PW)

Meine HomematicIP CCU3 läuft in einem anderen WLAN (192.168.0.1). Kann das dann überhaupt funktionieren?
Die Fehlermeldung die im Debug-Bereich von NodeRed erscheint ist "Velux Error: refuse login" und manchmal bringt er auch folgendes: "Velux Error: Start timeout reset the klf-200 please".

Was ist mein Fehler, bzw. wie kann ich weiter vorgehen?

Viele Grüße
F. K.

**Comment by PLCHome** [comment]
First of all, the project language is English.

> Hello,
> I try using the HomematicIP CCU3 and the installed NodeRed (v.0.20.5) (ie RedMatic v4.7.1) to connect the KLF 200 via the API. Unfortunately without success, so I hope for support. Unfortunately, I'm a total beginner in the field of NodeRed, etc., and I just can not go on now.
> 
> In NodeRed (ie RedMatic) I installed the "node-red-contrib-velux" and can use the three objects (Nodes, Api, Scenes).
> I pull the Velux Nodes in and select under DataSource the freshly furnished klf200-connection. (The host ip is 192.168.5.1 and the password is the wifi pw)
> 
> My HomematicIP CCU3 is running in a different WLAN (192.168.0.1). Can it work then?
> The error message that appears in the debug area of ​​NodeRed is "Velux Error: refuse login" and sometimes it also says "Velux Error: Start timeout reset the klf-200 please".
> 
> What is my mistake, or how can I proceed?
> 
> Best regards
> F.K.
> 

Second, you're wrong here. Node red can only be the node-red-contrib-velux.

I do not know the CCU3. On a Raspberry, a VLAN would have to be set up for the net 192.168.5.xxx. So that one can access it from the net 192.168.0.xxx. Otherwise you need a router that connects the networks 192.168.5.xxx and 192.168.0.xxx.
It may be possible to set the subnet mask to 255.255.0.0 on both devices. This makes it possible for the devices to communicate.

However, both devices must be physically in the same network.

I would suggest first to put a Raspberry or PC in the network with the KLF. Then install Nodered and test the function of the KLF.
